/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Completion struct {

	Type_ string `json:"type,omitempty"`

	Completion float64 `json:"completion,omitempty"`

	Percentage int32 `json:"percentage,omitempty"`

	SubCompletions map[string]Completion `json:"subCompletions,omitempty"`
}
