/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ComponentConfiguration struct {

	Separator string `json:"separator,omitempty"`

	Operation string `json:"operation,omitempty"`

	Relation string `json:"relation,omitempty"`

	Field string `json:"field,omitempty"`
}
