/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type DatamodelDefinition struct {

	FactSheets map[string]FactSheetDefinition `json:"factSheets,omitempty"`

	Relations map[string]Fs2FsRelationDefinition `json:"relations,omitempty"`

	Validators map[string]CustomValidator `json:"validators,omitempty"`

	ExternalIdFields map[string]ExternalIdFieldDefinition `json:"externalIdFields,omitempty"`

	Rules RulesDefinition `json:"rules,omitempty"`

	RelationMapping map[string]EffectiveRelationDefinition `json:"relationMapping,omitempty"`
}
