/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type EffectiveRelationDefinition struct {

	Direction string `json:"direction,omitempty"`

	ReverseName string `json:"reverseName,omitempty"`

	PersistedName string `json:"persistedName,omitempty"`
}
