/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ExternalIdType struct {

	Type_ string `json:"type,omitempty"`

	QuickSearch bool `json:"quickSearch,omitempty"`

	FullTextSearch bool `json:"fullTextSearch,omitempty"`

	UrlTemplate string `json:"urlTemplate,omitempty"`

	UniqueFactSheet bool `json:"uniqueFactSheet,omitempty"`

	ReadOnly bool `json:"readOnly,omitempty"`

	Validator string `json:"validator,omitempty"`
}
