/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type ExternalId struct {

	Type_ string `json:"type"`

	ExternalId string `json:"externalId,omitempty"`

	Comment string `json:"comment,omitempty"`

	Status string `json:"status,omitempty"`

	Url string `json:"url,omitempty"`
}
