/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type FactSheetDefinition struct {

	Relations []string `json:"relations,omitempty"`

	Config FactSheetConfiguration `json:"config,omitempty"`

	Fields map[string]DataType `json:"fields,omitempty"`
}
