/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type FactSheetResponse struct {

	ErrorMessage string `json:"errorMessage,omitempty"`

	Errors []ApiError `json:"errors,omitempty"`

	Data FactSheet `json:"data,omitempty"`
}
