/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Fs2FsRelationDefinition struct {

	From FromAndToDefinition `json:"from,omitempty"`

	To FromAndToDefinition `json:"to,omitempty"`

	ConstrainingRelations []string `json:"constrainingRelations,omitempty"`

	Constraints []string `json:"constraints,omitempty"`

	Fields map[string]DataType `json:"fields,omitempty"`
}
