/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type GqlComment struct {

	Message string `json:"message,omitempty"`

	Id string `json:"id,omitempty"`

	Status string `json:"status,omitempty"`

	UserId string `json:"userId,omitempty"`

	CreationTimestamp Instant `json:"creationTimestamp,omitempty"`

	FactSheetId string `json:"factSheetId,omitempty"`

	Replies []Reply `json:"replies,omitempty"`
}
