/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Instant struct {

	Nano int32 `json:"nano,omitempty"`

	EpochSecond int64 `json:"epochSecond,omitempty"`
}
