/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Location struct {

	Type_ string `json:"type"`

	Name string `json:"name,omitempty"`

	RawAddress string `json:"rawAddress,omitempty"`

	Latitude float64 `json:"latitude,omitempty"`

	Longitude float64 `json:"longitude,omitempty"`

	Accuracy string `json:"accuracy,omitempty"`

	GeoCity string `json:"geoCity,omitempty"`

	GeoCountryCode string `json:"geoCountryCode,omitempty"`

	GeoCountry string `json:"geoCountry,omitempty"`

	GeoAddress string `json:"geoAddress,omitempty"`

	GeoStreet string `json:"geoStreet,omitempty"`

	GeoPostalCode string `json:"geoPostalCode,omitempty"`
}
