/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type QueryResponse struct {

	Status string `json:"status,omitempty"`

	Type_ string `json:"type,omitempty"`

	Message string `json:"message,omitempty"`

	Errors []ApiError `json:"errors,omitempty"`

	Total int64 `json:"total,omitempty"`

	Data SavedQuery `json:"data,omitempty"`
}
