/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

import (
	"time"
)

type Relation struct {

	Id string `json:"id,omitempty"`

	FromId string `json:"fromId"`

	ToId string `json:"toId"`

	FactSheet FactSheet `json:"factSheet,omitempty"`

	Type_ string `json:"type"`

	ActiveFrom time.Time `json:"activeFrom,omitempty"`

	ActiveUntil time.Time `json:"activeUntil,omitempty"`

	ConstrainingRelations []Relation `json:"constrainingRelations,omitempty"`

	Fields map[string]LxField `json:"fields,omitempty"`

	IntentionallyNotSet []string `json:"intentionallyNotSet,omitempty"`

	Status string `json:"status,omitempty"`
}
