/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Reply struct {

	Id string `json:"id,omitempty"`

	UserId string `json:"userId,omitempty"`

	Message string `json:"message"`

	CreationTimestamp Instant `json:"creationTimestamp,omitempty"`
}
