/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type StartSyncWorkspaceRequest struct {

	WorkspaceId string `json:"workspaceId,omitempty"`

	WorkspaceName string `json:"workspaceName"`

	UserId string `json:"userId,omitempty"`

	EamBasePath string `json:"eamBasePath"`

	UseSynclog bool `json:"useSynclog,omitempty"`
}
