/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type StatusType struct {

	Type_ string `json:"type,omitempty"`

	QuickSearch bool `json:"quickSearch,omitempty"`

	FullTextSearch bool `json:"fullTextSearch,omitempty"`

	Values []string `json:"values,omitempty"`
}
