/* 
 * LeanIX Pathfinder REST API
 *
 * Core application for storage and analysis of IT landscape data
 *
 * OpenAPI spec version: 0.1.10-SNAPSHOT
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

package swagger

type Tag struct {

	Id string `json:"id,omitempty"`

	Name string `json:"name"`

	Description string `json:"description,omitempty"`

	BgColor string `json:"bgColor,omitempty"`

	Status string `json:"status"`
}
